name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get install -y libmagick++-dev

    - name: Install R package dependencies with retries
      run: |
        RETRY_COUNT=5
        RETRY_DELAY=10
        for i in $(seq 1 $RETRY_COUNT); do
          Rscript -e 'install.packages("devtools")' && break || sleep $RETRY_DELAY
        done
        for i in $(seq 1 $RETRY_COUNT); do
          Rscript -e 'install.packages("remotes")' && break || sleep $RETRY_DELAY
        done
        for i in $(seq 1 $RETRY_COUNT); do
          Rscript -e 'remotes::install_deps(dependencies = TRUE)' && break || sleep $RETRY_DELAY
        done
      shell: bash

    - name: Install DropletQC from GitHub with retries
      run: |
        RETRY_COUNT=5
        RETRY_DELAY=10
        for i in $(seq 1 $RETRY_COUNT); do
          Rscript -e 'devtools::install_github("powellgenomicslab/DropletQC")' && break || sleep $RETRY_DELAY
        done
      shell: bash

    - name: Check package
      run: |
        R CMD check --no-manual --as-cran
      shell: Rscript {0}
